//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class bultin_paie
    {
        public int id_bulltin { get; set; }
        public string mois { get; set; }
        public string année { get; set; }
        public Nullable<double> net_a_apyer { get; set; }
        public Nullable<double> salair_poste { get; set; }
        public Nullable<double> totale_cotisable { get; set; }
        public Nullable<double> net_imposable { get; set; }
        public Nullable<double> Total_Retenu { get; set; }
        public string mode_reglement { get; set; }
        public Nullable<int> id_salarié { get; set; }
    }
}
