//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cna
    {
        public int id_cnas { get; set; }
        public string nom_cnas { get; set; }
        public string adress_cnas { get; set; }
        public string wilaya { get; set; }
        public string téléphone { get; set; }
    }
}
