//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Constantt
    {
        public int id_const { get; set; }
        public string Code { get; set; }
        public string Intitulé { get; set; }
        public Nullable<double> Valeur { get; set; }
    }
}
