//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class contrat
    {
        public int id_contrat { get; set; }
        public Nullable<System.DateTime> date_embouche { get; set; }
        public string frequnce_Paie { get; set; }
        public Nullable<double> base_paie { get; set; }
        public Nullable<int> id_salarié { get; set; }
        public string mode_reglement { get; set; }
        public Nullable<double> salair_base { get; set; }
        public Nullable<double> taux_jour { get; set; }
        public Nullable<double> taux_heure { get; set; }
        public string statu { get; set; }
        public Nullable<System.DateTime> date_fin { get; set; }
        public Nullable<System.DateTime> date_sotie { get; set; }
        public string mod_calcule { get; set; }
        public string rémunération { get; set; }
        public Nullable<double> montont_exoneration { get; set; }
        public string mode_paiment { get; set; }
        public string banque { get; set; }
        public string CCP { get; set; }
        public string Rip { get; set; }
        public string exoneration_de_irg { get; set; }
    }
}
