//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entreprise
    {
        public int id_entreprise { get; set; }
        public string nom_ent { get; set; }
        public string adresse { get; set; }
        public string form_juriduique { get; set; }
        public string email { get; set; }
        public string Activité { get; set; }
        public string rejistre_comerce { get; set; }
        public string Identifiant_Fiscal { get; set; }
        public string code_postal { get; set; }
        public string Ville { get; set; }
        public string fax { get; set; }
        public Nullable<int> id_user { get; set; }
        public string téléphone { get; set; }
    }
}
