//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class formule
    {
        public int id_formule { get; set; }
        public Nullable<double> nombre { get; set; }
        public Nullable<double> Base { get; set; }
        public Nullable<double> taux { get; set; }
        public Nullable<double> montont { get; set; }
        public Nullable<int> id_rubrique { get; set; }
        public string equoiation { get; set; }
    }
}
