//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class paieEntities12 : DbContext
    {
        public paieEntities12()
            : base("name=paieEntities12")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Banque> Banques { get; set; }
        public virtual DbSet<baréme_IRG> baréme_IRG { get; set; }
        public virtual DbSet<bultin_paie> bultin_paie { get; set; }
        public virtual DbSet<Cna> Cnas { get; set; }
        public virtual DbSet<contrat> contrats { get; set; }
        public virtual DbSet<Départemetent> Départemetent { get; set; }
        public virtual DbSet<Entreprise> Entreprises { get; set; }
        public virtual DbSet<formule> formules { get; set; }
        public virtual DbSet<login> logins { get; set; }
        public virtual DbSet<ruberique_bulltin> ruberique_bulltin { get; set; }
        public virtual DbSet<rubrique> rubriques { get; set; }
        public virtual DbSet<salariés> salariés { get; set; }
        public virtual DbSet<teste> testes { get; set; }
        public virtual DbSet<Barém_cnas> Barém_cnas { get; set; }
        public virtual DbSet<Constantt> Constantts { get; set; }
    }
}
