//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ruberique_bulltin
    {
        public int id { get; set; }
        public Nullable<int> id_bulltin { get; set; }
        public string code { get; set; }
        public string nbr_base { get; set; }
        public string taux { get; set; }
        public string gain { get; set; }
        public string retenue { get; set; }
        public string libellé { get; set; }
    }
}
