//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class rubrique
    {
        public int id_rubrique { get; set; }
        public string code { get; set; }
        public string libellé { get; set; }
        public Nullable<int> compt { get; set; }
        public string abrégé { get; set; }
        public Nullable<System.DateTime> date_de_création { get; set; }
        public string Compte_contable { get; set; }
        public Nullable<double> montant { get; set; }
        public string imopsalble { get; set; }
        public Nullable<bool> cotisable { get; set; }
        public Nullable<bool> sens { get; set; }
        public Nullable<bool> inclur_dans_brut { get; set; }
        public Nullable<bool> ne_pas_inclur_dans_masse_salarié { get; set; }
        public Nullable<bool> reporter_aprée_cloture_mois { get; set; }
        public string imopsalblee { get; set; }
        public Nullable<double> valeur_initia { get; set; }
        public string Type_val { get; set; }
        public Nullable<bool> etat { get; set; }
    }
}
