//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class salariés
    {
        public string matruculation { get; set; }
        public string nom { get; set; }
        public string prénom { get; set; }
        public Nullable<System.DateTime> dat_naiss { get; set; }
        public string lieu_naiss { get; set; }
        public string commune_naiss { get; set; }
        public string wilaya_naiss { get; set; }
        public string prénom_pére { get; set; }
        public string nom_mére { get; set; }
        public string prénom_mére { get; set; }
        public string sexe { get; set; }
        public string situation_famille { get; set; }
        public string nationalité { get; set; }
        public string adresse_compléte { get; set; }
        public Nullable<int> code_postal { get; set; }
        public string matruculationss { get; set; }
        public int id_salarié { get; set; }
        public Nullable<int> personns_charge { get; set; }
        public Nullable<int> Personnes_charge { get; set; }
        public Nullable<int> dans_enfant_scolarisé { get; set; }
        public string état_sal { get; set; }
        public Nullable<System.DateTime> date_entrée { get; set; }
        public Nullable<System.DateTime> date_sortie { get; set; }
        public string mode_calcul { get; set; }
        public string nom_conjoin { get; set; }
        public string situation_conjoin { get; set; }
        public string adresse { get; set; }
        public string code_wilaya { get; set; }
        public string email { get; set; }
        public string num_sécurité_socialeee { get; set; }
        public string photos { get; set; }
        public string téléphone { get; set; }
        public Nullable<int> id_ent { get; set; }
    }
}
